"""Generate a clean, runnable CadQuery script from a Studio feature list.

Mirrors kernel._apply's body bookkeeping so the exported script reproduces
exactly what the app shows, and ends by combining every live body for export.
"""
from __future__ import annotations

SOLID_TYPES = {"extrude", "revolve", "sweep", "loft"}


def _fmt_plane(p: dict) -> str:
    # Resolve through the same code the kernel uses so the exported script and
    # the app can never disagree about where a datum plane is.
    if not (p.get("origin") and p.get("normal")) and not (p.get("offset")):
        base = p.get("base", "XY")
        return f'cq.Plane.named("{base if base in NAMED else "XY"}")'
    from .kernel import _plane_from_params
    pl = _plane_from_params(p)
    o = (round(pl.origin.x, 6), round(pl.origin.y, 6), round(pl.origin.z, 6))
    x = (round(pl.xDir.x, 6), round(pl.xDir.y, 6), round(pl.xDir.z, 6))
    n = (round(pl.zDir.x, 6), round(pl.zDir.y, 6), round(pl.zDir.z, 6))
    return f"cq.Plane(origin={o}, xDir={x}, normal={n})"


NAMED = {"XY", "XZ", "YZ", "front", "back", "left", "right", "top", "bottom"}


def _emit_one_loop(lines: list[str], lvar: str, basevar: str, loop: list):
    """Emit one closed loop into lvar, starting from basevar's workplane."""
    if not loop:
        return
    if len(loop) == 1 and loop[0]["type"] == "circle":
        s = loop[0]
        lines.append(f"{lvar} = {basevar}.moveTo({float(s['cx'])}, {float(s['cy'])}).circle({float(s['r'])})")
        return
    first = loop[0]
    sx, sy = (first.get("x1"), first.get("y1")) if first["type"] in ("line", "arc") else \
        (first["points"][0][0], first["points"][0][1])
    lines.append(f"{lvar} = {basevar}.moveTo({float(sx)}, {float(sy)})")
    for s in loop:
        t = s["type"]
        if t == "line":
            lines.append(f"{lvar} = {lvar}.lineTo({float(s['x2'])}, {float(s['y2'])})")
        elif t == "arc":
            lines.append(f"{lvar} = {lvar}.threePointArc(({float(s['mx'])}, {float(s['my'])}), ({float(s['x2'])}, {float(s['y2'])}))")
        elif t == "spline":
            pts = [(float(a), float(b)) for a, b in s["points"]]
            lines.append(f"{lvar} = {lvar}.spline({pts})")
        elif t == "circle":
            lines.append(f"{lvar} = {lvar}.circle({float(s['r'])})")
    lines.append(f"{lvar} = {lvar}.close()")


def _emit_loops(lines: list[str], var: str, loops: list, nv) -> None:
    """Single loop: chain directly on the sketch var. Multiple loops (e.g. a
    profile with holes): emit each as its own loop_N variable joined with
    .add(), the form the importer reconstructs back into separate loops."""
    loops = [lp for lp in loops if lp]
    if len(loops) <= 1:
        if loops:
            _emit_one_loop(lines, var, var, loops[0])
        return
    lvs = []
    for lp in loops:
        lv = nv("loop")
        lvs.append(lv)
        _emit_one_loop(lines, lv, var, lp)
    lines.append(f"{var} = {var}" + "".join(f".add({x})" for x in lvs))


def _solid_expr(sketch_var: str, feat: dict) -> str:
    t = feat["type"]
    p = feat.get("params", {})
    if t == "extrude":
        dist = float(p.get("distance", 1))
        direction = p.get("direction", "normal")
        both = direction == "symmetric"
        if direction == "reverse":
            dist = -abs(dist)
        return f"{sketch_var}.extrude({dist}, both={both}, combine=False)"
    if t == "revolve":
        angle = float(p.get("angle", 360))
        a_s = tuple(round(float(v), 6) for v in p.get("axis_start", [0, 0, 0]))
        a_e = tuple(round(float(v), 6) for v in p.get("axis_end", [0, 1, 0]))
        return f"{sketch_var}.revolve({angle}, {a_s}, {a_e})"
    return f"{sketch_var}"


def _axis_sketch_line(features, sid):
    """True if sketch `sid` holds a line/spline usable as a revolve axis — mirrors
    the kernel's _axis_from_sketch so codegen only takes that path when it works."""
    if not sid:
        return False
    for f in features:
        if f.get("id") == sid and f.get("type") == "sketch":
            for loop in f.get("params", {}).get("loops", []):
                for s in loop:
                    if s.get("type") == "line":
                        return True
                    if s.get("type") == "spline" and len(s.get("points", [])) >= 2:
                        return True
    return False


def generate(features: list[dict]) -> str:
    lines = ["import cadquery as cq", "import math", "", "# Generated by Studio CAD", ""]
    plane_vars: dict[str, str] = {}
    sketch_vars: dict[str, str] = {}
    bodies: dict[str, str] = {}   # body id -> var name (preserves order)
    active = [None]
    counters = {"plane": 0, "sketch": 0, "body": 0, "tool": 0, "loop": 0}

    def nv(kind: str) -> str:
        counters[kind] += 1
        return f"{kind}_{counters[kind]}"

    def resolve_body(tid):
        if tid and tid in bodies:
            return tid
        if active[0] and active[0] in bodies:
            return active[0]
        return next(reversed(bodies)) if bodies else None

    def plane_ref(ref):
        if isinstance(ref, dict) and ref.get("origin"):
            return _fmt_plane(ref)
        if isinstance(ref, str) and ref in plane_vars:
            return plane_vars[ref]
        if isinstance(ref, str) and ref in NAMED:
            return f'cq.Plane.named("{ref}")'
        return 'cq.Plane.named("XY")'

    # Fillet/chamfer (picked edges), shell (picked faces) and revolve-about-a-
    # picked-edge reference geometry by 3-D point, not by name. Emit a selector
    # that mirrors the kernel so the generated script reproduces the SAME pick.
    def _needs_near(feats):
        for f in feats:
            if f.get("suppressed"):
                continue
            pp = f.get("params", {})
            if f["type"] in ("fillet", "chamfer") and isinstance(pp.get("edges"), list):
                return True
            if f["type"] == "shell" and isinstance(pp.get("faces"), list):
                return True
            if f["type"] == "revolve" and pp.get("axis_edge"):
                return True
        return False

    if _needs_near(features):
        lines += [
            "",
            "def _near(objs, pts):",
            '    """Pick the edges/faces nearest each 3-D point — matches Studio\'s selection."""',
            "    from OCP.BRepExtrema import BRepExtrema_DistShapeShape",
            "    from OCP.BRepBuilderAPI import BRepBuilderAPI_MakeVertex",
            "    from OCP.gp import gp_Pnt",
            "    chosen = []",
            "    for _p in pts:",
            "        _v = BRepBuilderAPI_MakeVertex(gp_Pnt(float(_p[0]), float(_p[1]), float(_p[2]))).Shape()",
            "        _best, _bd = None, float('inf')",
            "        for _o in objs:",
            "            _d = BRepExtrema_DistShapeShape(_v, _o.wrapped)",
            "            if _d.IsDone() and _d.NbSolution() > 0 and _d.Value() < _bd:",
            "                _bd, _best = _d.Value(), _o",
            "        if _best is not None and _best not in chosen:",
            "            chosen.append(_best)",
            "    return chosen",
        ]

    for f in features:
        if f.get("suppressed"):
            continue
        t = f["type"]
        fid = f["id"]
        p = f.get("params", {})

        if t == "datum_plane":
            v = nv("plane")
            plane_vars[fid] = v
            lines.append(f"{v} = {_fmt_plane(p)}")
        elif t == "import_solid":
            # The STEP geometry isn't embedded in the script, but we still must
            # register a body var — otherwise any downstream op on it (pattern,
            # boolean, fillet, …) finds no body and gets silently dropped.
            bv = nv("body")
            bodies[fid] = bv
            active[0] = fid
            nm = str(f.get("name") or "imported").replace('"', "'")
            fmt = str(p.get("format") or "step").lower()
            ext = "step" if fmt in ("step", "stp") else fmt
            lines.append("")
            lines.append(f'# Imported solid "{nm}" — its geometry is NOT embedded in this script.')
            lines.append(f'# Put "{nm}.{ext}" next to this file (or fix the path) to reproduce it.')
            if ext in ("step", "stp"):
                lines.append(f'{bv} = cq.importers.importStep("{nm}.{ext}")')
            else:
                lines.append(f'{bv} = cq.Workplane()  # TODO: load "{nm}.{ext}"')
        elif t == "sketch":
            v = nv("sketch")
            sketch_vars[fid] = v
            lines.append("")
            lines.append(f"# {f.get('name', 'Sketch')}")
            lines.append(f"{v} = cq.Workplane({plane_ref(p.get('plane', 'XY'))})")
            _emit_loops(lines, v, p.get("loops", []), nv)
        elif t in SOLID_TYPES:
            sv = sketch_vars.get(p.get("sketch"), "cq.Workplane()")
            pre = []     # extra lines emitted before the body assignment
            expr = None  # None → can't resolve this feature; emit a comment and skip
            if t == "sweep":
                prof, path = sketch_vars.get(p.get("sketch")), sketch_vars.get(p.get("path"))
                if prof and path:
                    expr = f"{prof}.sweep({path})"
            elif t == "loft":
                secs = [sketch_vars[s] for s in (p.get("sections") or []) if s in sketch_vars]
                if len(secs) >= 2:
                    expr = secs[0] + "".join(f".add({s})" for s in secs[1:]) + f".loft(ruled={bool(p.get('ruled', False))})"
            elif t == "revolve" and p.get("axis_edge"):
                ang = float(p.get("angle", 360))
                if bodies:   # resolve the axis from the picked edge on existing bodies
                    pt = [round(float(c), 6) for c in p["axis_edge"]]
                    alled = " + ".join(f"{v}.edges().vals()" for v in bodies.values())
                    pre.append(f"_rax = _near({alled}, [{pt!r}])[0]")
                    expr = f"{sv}.revolve({ang}, _rax.startPoint().toTuple(), _rax.endPoint().toTuple())"
                else:        # no prior body to pick from — keep the script runnable
                    pre.append("# picked revolve axis needs a prior body; falling back to the default axis")
                    expr = _solid_expr(sv, f)
            elif t == "revolve" and p.get("axis_sketch") in sketch_vars:
                # Only valid if that sketch holds a line (kernel raises otherwise → no body)
                if _axis_sketch_line(features, p["axis_sketch"]):
                    ang = float(p.get("angle", 360))
                    asv = sketch_vars[p["axis_sketch"]]
                    pre.append(f"_axl = [_e for _e in {asv}.edges().vals() if _e.geomType() in ('LINE', 'BSPLINE')]")
                    pre.append(f"_rax = _axl[0] if _axl else {asv}.edges().vals()[0]")
                    expr = f"{sv}.revolve({ang}, _rax.startPoint().toTuple(), _rax.endPoint().toTuple())"
                # else expr stays None → skipped, matching the kernel erroring this feature
            else:
                expr = _solid_expr(sv, f)
            op = p.get("operation", "new")
            lines.append("")
            lines.append(f"# {f.get('name', t)}")
            if expr is None:
                lines.append(f"# (skipped: {t} could not be resolved from the available sketches)")
                continue
            lines.extend(pre)
            if op == "new" or not bodies:
                bv = nv("body")
                bodies[fid] = bv
                active[0] = fid
                lines.append(f"{bv} = {expr}")
            else:
                tgt = resolve_body(p.get("target"))
                if tgt is None:
                    bv = nv("body")
                    bodies[fid] = bv
                    active[0] = fid
                    lines.append(f"{bv} = {expr}")
                else:
                    tool = nv("tool")
                    lines.append(f"{tool} = {expr}")
                    m = {"cut": "cut", "intersect": "intersect"}.get(op, "union")
                    lines.append(f"{bodies[tgt]} = {bodies[tgt]}.{m}({tool})")
                    active[0] = tgt
        elif t == "hole":
            tgt = resolve_body(p.get("target"))
            if tgt is None:
                continue
            bv = bodies[tgt]
            c = (round(float(p.get("cx", 0)), 6), round(float(p.get("cy", 0)), 6), round(float(p.get("cz", 0)), 6))
            n = tuple(round(float(v), 6) for v in p.get("normal", [0, 0, 1]))
            r = float(p.get("diameter", 5)) / 2.0
            lines.append(f"# {f.get('name', 'Hole')}")
            lines.append(f"_hp = cq.Plane(origin={c}, normal={n})")
            depth = "999" if p.get("through") else str(abs(float(p.get('depth', 5))))
            lines.append(f"_tool = cq.Workplane(_hp).circle({r}).extrude(-{depth})")
            if p.get("counterbore"):
                lines.append(f"_tool = _tool.union(cq.Workplane(_hp).circle({float(p.get('cbore_diameter', r * 4)) / 2.0}).extrude(-{abs(float(p.get('cbore_depth', r)))}))")
            lines.append(f"{bv} = {bv}.cut(_tool)")
            active[0] = tgt
        elif t in ("fillet", "chamfer", "shell"):
            tgt = resolve_body(p.get("target"))
            if tgt is None:
                continue
            bv = bodies[tgt]
            lines.append(f"# {f.get('name', t)}")
            if t == "shell":
                sel = p.get("faces")
                thick = -abs(float(p["thickness"]))
                if isinstance(sel, list) and sel:   # remove only the picked faces
                    pts = [[round(float(c), 6) for c in pt] for pt in sel]
                    lines.append(f"{bv} = {bv}.newObject(_near({bv}.faces().vals(), {pts!r})).shell({thick})")
                else:
                    lines.append(f"{bv} = {bv}.shell({thick})")
            else:
                sel = p.get("edges")
                meth = "fillet" if t == "fillet" else "chamfer"
                val = float(p["radius"]) if t == "fillet" else float(p["distance"])
                if isinstance(sel, list) and sel:   # only the picked edges, not all
                    pts = [[round(float(c), 6) for c in pt] for pt in sel]
                    lines.append(f"{bv} = {bv}.newObject(_near({bv}.edges().vals(), {pts!r})).{meth}({val})")
                else:
                    lines.append(f"{bv} = {bv}.edges().{meth}({val})")
            active[0] = tgt
        elif t == "mirror":
            tgt = resolve_body(p.get("target"))
            if tgt is None:
                continue
            bv = bodies[tgt]
            plane = p.get("plane", "XZ")
            lines.append(f"# {f.get('name', 'Mirror')}")
            if p.get("merge"):
                lines.append(f'{bv} = {bv}.union({bv}.mirror("{plane}"))')
                active[0] = tgt
            else:
                nbv = nv("body")
                bodies[fid] = nbv
                lines.append(f'{nbv} = {bv}.mirror("{plane}")')
                active[0] = fid
        elif t == "boolean":
            tgt = p.get("target")
            if tgt not in bodies:
                continue
            op = p.get("operation", "union")
            m = {"cut": "cut", "intersect": "intersect"}.get(op, "union")
            lines.append(f"# {f.get('name', 'Boolean')}")
            for tool in p.get("tools", []):
                if tool in bodies and tool != tgt:
                    lines.append(f"{bodies[tgt]} = {bodies[tgt]}.{m}({bodies[tool]})")
                    del bodies[tool]
            active[0] = tgt
        elif t in ("linear_pattern", "circular_pattern"):
            tgt = resolve_body(p.get("target"))
            if tgt is None:
                continue
            bv = bodies[tgt]
            lines.append(f"# {f.get('name', t)}")
            lines.append(f"_base = {bv}.val()")
            if t == "linear_pattern":
                dx, dy, dz = (list(p.get("dir", [1, 0, 0])) + [0, 0, 0])[:3]
                count = int(p.get("count", 2))
                sp = float(p.get("spacing", 10))
                lines.append(f"for _i in range(1, {count}):")
                lines.append(f"    {bv} = {bv}.union(cq.Workplane().add(_base).translate(({dx}*{sp}*_i, {dy}*{sp}*_i, {dz}*{sp}*_i)))")
            else:
                a_s = tuple(float(v) for v in p.get("axis_start", [0, 0, 0]))
                a_e = tuple(float(v) for v in p.get("axis_end", [0, 0, 1]))
                count = int(p.get("count", 4))
                ang = float(p.get("angle", 360))
                lines.append(f"for _i in range(1, {count}):")
                lines.append(f"    {bv} = {bv}.union(cq.Workplane().add(_base).rotate({a_s}, {a_e}, {ang}/{count}*_i))")
            active[0] = tgt

    # ---- combine live bodies + export ----
    live = list(bodies.values())
    lines.append("")
    lines.append("# Combine bodies and export")
    if not live:
        lines.append("result = cq.Workplane()")
    else:
        lines.append(f"result = {live[0]}")
        for v in live[1:]:
            lines.append("try:")
            lines.append(f"    result = result.union({v})")
            lines.append("except Exception:")
            lines.append(f"    result = result.add({v})")
    lines.append('cq.exporters.export(result, "model.step")')
    lines.append('cq.exporters.export(result, "model.stl")')
    lines.append('# show_object(result)  # for CQ-editor')
    return "\n".join(lines)
